import { createStyleHook } from "../styles/createStyleHook"

const DataVaultStyles = {
  container: {
    display: "flex",
    flexDirection: "column" as const,
    height: "100%",
    background: "var(--background)",
    color: "var(--text)",
    fontFamily: "var(--font-mono, monospace)",
    fontSize: "13px",
  },
  header: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "16px 20px 12px",
    borderBottom: "1px solid var(--shade-2)",
  },
  headerTitle: {
    fontWeight: 600,
    fontSize: "14px",
    margin: 0,
  },
  headerSub: {
    fontSize: "11px",
    color: "var(--text-muted)",
    margin: 0,
    marginLeft: "4px",
  },
  // ── Tabs ────────────────────────────────────────────────────────
  tabBar: {
    display: "flex",
    flexDirection: "row" as const,
    borderBottom: "1px solid var(--shade-2)",
    padding: "0 12px",
  },
  tab: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    padding: "8px 12px",
    cursor: "pointer",
    color: "var(--text-muted)",
    borderBottom: "2px solid transparent",
    fontSize: "12px",
    userSelect: "none" as const,
  },
  tabActive: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    padding: "8px 12px",
    cursor: "pointer",
    color: "var(--link-color)",
    borderBottom: "2px solid var(--link-color)",
    fontSize: "12px",
    fontWeight: 600,
    userSelect: "none" as const,
  },
  tabContent: {
    flex: 1,
    overflow: "hidden",
    display: "flex",
  },
  // ── Pane ────────────────────────────────────────────────────────
  tabPane: {
    display: "flex",
    flexDirection: "row" as const,
    flex: 1,
    overflow: "hidden",
  },
  // ── Table list (left sidebar) ───────────────────────────────────
  tableList: {
    width: "180px",
    minWidth: "180px",
    borderRight: "1px solid var(--shade-2)",
    overflowY: "auto" as const,
    padding: "8px 0",
  },
  tableItem: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "7px 14px",
    cursor: "pointer",
    color: "var(--text-muted)",
  },
  tableItemActive: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "7px 14px",
    cursor: "pointer",
    background: "var(--shade-1)",
    color: "var(--text)",
    borderLeft: "2px solid var(--link-color)",
  },
  tableItemName: {
    margin: 0,
    fontSize: "12px",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  tableItemCount: {
    margin: 0,
    fontSize: "11px",
    color: "var(--text-muted)",
    marginLeft: "6px",
    flexShrink: 0,
  },
  sectionLabel: {
    margin: "6px 14px",
    fontSize: "10px",
    color: "var(--text-muted)",
    textTransform: "uppercase" as const,
    letterSpacing: "0.05em",
  },
  // ── Row viewer (right pane) ─────────────────────────────────────
  rowViewer: {
    flex: 1,
    display: "flex",
    flexDirection: "column" as const,
    overflow: "hidden",
  },
  rowViewerHeader: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "10px 14px",
    borderBottom: "1px solid var(--shade-2)",
  },
  searchInput: {
    flex: 1,
    background: "var(--shade-1)",
    border: "1px solid var(--shade-2)",
    borderRadius: "6px",
    padding: "5px 10px",
    color: "var(--text)",
    fontSize: "12px",
  },
  rowCount: {
    margin: 0,
    fontSize: "11px",
    color: "var(--text-muted)",
    flexShrink: 0,
  },
  // ── Table ───────────────────────────────────────────────────────
  tableWrapper: {
    flex: 1,
    overflowX: "auto" as const,
    overflowY: "auto" as const,
  },
  table: {
    width: "100%",
    borderCollapse: "collapse" as const,
    fontSize: "12px",
  },
  th: {
    textAlign: "left" as const,
    padding: "6px 12px",
    background: "var(--shade-1)",
    borderBottom: "1px solid var(--shade-2)",
    color: "var(--text-muted)",
    fontWeight: 600,
    whiteSpace: "nowrap" as const,
    position: "sticky" as const,
    top: 0,
  },
  tr: {
    borderBottom: "1px solid var(--shade-1)",
  },
  td: {
    padding: "5px 12px",
    verticalAlign: "top" as const,
    maxWidth: "240px",
  },
  cellValue: {
    display: "block",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
    color: "var(--text)",
  },
  deleteBtn: {
    background: "none",
    border: "none",
    cursor: "pointer",
    color: "var(--text-muted)",
    padding: "2px 4px",
    borderRadius: "4px",
    display: "flex",
    alignItems: "center",
  },
  // ── Pagination ──────────────────────────────────────────────────
  pagination: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "8px 14px",
    borderTop: "1px solid var(--shade-2)",
    justifyContent: "center",
  },
  pageBtn: {
    background: "var(--shade-1)",
    border: "1px solid var(--shade-2)",
    borderRadius: "6px",
    padding: "4px 10px",
    cursor: "pointer",
    color: "var(--text)",
    fontSize: "12px",
  },
  pageInfo: {
    margin: 0,
    fontSize: "11px",
    color: "var(--text-muted)",
  },
  centered: {
    flex: 1,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "var(--text-muted)",
    padding: "40px",
  },
  // ── Redis ────────────────────────────────────────────────────────
  keyList: {
    width: "240px",
    minWidth: "240px",
    borderRight: "1px solid var(--shade-2)",
    overflowY: "auto" as const,
  },
  keyName: {
    margin: 0,
    fontSize: "12px",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
    maxWidth: "160px",
  },
  rowItemRight: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
  },
  valuePane: {
    flex: 1,
    overflowY: "auto" as const,
    padding: "12px",
  },
  valueCode: {
    background: "var(--shade-1)",
    borderRadius: "6px",
    padding: "12px",
    fontSize: "11px",
    overflow: "auto" as const,
    maxHeight: "400px",
    color: "var(--text)",
    whiteSpace: "pre-wrap" as const,
    wordBreak: "break-all" as const,
  },
  // ── FalkorDB ─────────────────────────────────────────────────────
  statRow: {
    display: "flex",
    gap: "12px",
    padding: "12px 14px",
    borderBottom: "1px solid var(--shade-2)",
  },
  statCard: {
    background: "var(--shade-1)",
    borderRadius: "8px",
    padding: "10px 16px",
    minWidth: "80px",
    textAlign: "center" as const,
  },
  statValue: {
    margin: 0,
    fontSize: "20px",
    fontWeight: 700,
    color: "var(--text)",
  },
  statLabel: {
    margin: 0,
    fontSize: "10px",
    color: "var(--text-muted)",
    marginTop: "2px",
  },
  nodeList: {
    flex: 1,
    overflowY: "auto" as const,
    padding: "12px",
    display: "flex",
    flexDirection: "column" as const,
    gap: "8px",
  },
  nodeCard: {
    background: "var(--shade-1)",
    borderRadius: "6px",
    padding: "8px 12px",
    border: "1px solid var(--shade-2)",
  },
  // ── Files ────────────────────────────────────────────────────────
  fileGrid: {
    flex: 1,
    overflowY: "auto" as const,
    padding: "12px",
    display: "flex",
    flexDirection: "column" as const,
    gap: "8px",
  },
  fileCard: {
    background: "var(--shade-1)",
    borderRadius: "8px",
    padding: "10px 14px",
    border: "1px solid var(--shade-2)",
  },
  fileCardTop: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "4px",
  },
  fileName: {
    margin: 0,
    fontWeight: 600,
    fontSize: "12px",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
    maxWidth: "260px",
  },
  fileMeta: {
    margin: 0,
    fontSize: "11px",
    color: "var(--text-muted)",
  },
  fileLink: {
    fontSize: "11px",
    color: "var(--link-color)",
    marginTop: "4px",
    display: "block",
  },
  native: {},
}

export const useDataVaultStyles =
  createStyleHook<typeof DataVaultStyles>(DataVaultStyles)
