#!/bin/bash
# Env dosyalarini birlestirip Dokploy icin normalize eder
# Kullanim: bash scripts/merge-env-dokploy.sh > .env.dokploy

ROOT="$(cd "$(dirname "$0")/.." && pwd)"

declare -A ENV_MAP

# Env dosyasini oku, onceki degerler korunur (son dosya kazanir istersen sirasini degistir)
load_env() {
  local file="$1"
  if [ ! -f "$file" ]; then return; fi
  while IFS= read -r line || [ -n "$line" ]; do
    # Yorum ve bos satirlari atla
    [[ "$line" =~ ^#.*$ || -z "$line" ]] && continue
    # KEY=VALUE formatinda mi?
    if [[ "$line" =~ ^([A-Za-z_][A-Za-z0-9_]*)=(.*)$ ]]; then
      key="${BASH_REMATCH[1]}"
      val="${BASH_REMATCH[2]}"
      ENV_MAP["$key"]="$val"
    fi
  done < "$file"
}

# Dusuk oncelikten yuksege yukle (son dosya kazanir)
load_env "$ROOT/.env"
load_env "$ROOT/apps/api/.env"
load_env "$ROOT/apps/api/.env.production.local"

# Dokploy icin override'lar (compose zaten bunlari set ediyor ama referans icin)
ENV_MAP["NODE_ENV"]="production"
ENV_MAP["DISABLE_DB_SSL"]="true"

# Gereksiz/local-only key'leri cikar
SKIP_KEYS=(
  "NIXPACKS_NODE_VERSION"
  "NEXTAUTH_URL"      # compose env'den gelecek
  "WS_SERVER_URL"     # compose icinde
)

for key in "${SKIP_KEYS[@]}"; do
  unset ENV_MAP["$key"]
done

# Cikti
echo "# Generated by scripts/merge-env-dokploy.sh"
echo "# $(date)"
echo ""

for key in $(echo "${!ENV_MAP[@]}" | tr ' ' '\n' | sort); do
  echo "${key}=${ENV_MAP[$key]}"
done
